# openapi.yaml
swagger: '2.0'
info:
  title: tap-rx-config
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://us-central1-taprx-9c82f.cloudfunctions.net/hello_world_function
      responses:
        '200':
          description: A successful response
          schema:
            type: string
