# openapi.yaml
swagger: '2.0'
info:
  title: tap-rx-config
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://us-central1-taprx-9c82f.cloudfunctions.net/hello_world_function
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /register:
    get:
      summary: Register a user for TapRx
      operationId: register
      x-google-backend:
        address: https://us-central1-taprx-9c82f.cloudfunctions.net/register_user_function
      responses:
        '200':
          description: "Success."
          schema:
            type: string
        '400':
          description: "An element in the JSON request is missing or invalid."
          schema:
            type: string
securityDefinitions:
  auth0_jwt:
    authorizationUrl: "https://dev-yg38dkcvqkoi1ekn.us.auth0.com/authorize"
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://dev-yg38dkcvqkoi1ekn.us.auth0.com/"
    x-google-jwks_uri: "https://dev-yg38dkcvqkoi1ekn.us.auth0.com/.well-known/jwks.json"
    x-google-audiences: "https://tap-rx/"