name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform-deploy:
    name: Terraform Deployment
    runs-on: ubuntu-latest
    outputs:
      terraform_changes: ${{ steps.check_changes.outputs.terraform_changes }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Ensure all necessary commits are fetched

    - name: Check for Terraform Changes
      id: check_changes
      run: |
        echo "Checking for changes in Terraform files..."
        if git diff --name-only HEAD~1 HEAD | grep 'terraform/'; then
          echo "Changes found in Terraform files"
          echo "terraform_changes=true" >> $GITHUB_ENV
        else
          echo "No changes found in Terraform files"
          echo "terraform_changes=false" >> $GITHUB_ENV
        fi

    - name: Terraform Init and Apply
      if: env.terraform_changes == 'true'
      run: |
        cd terraform
        echo "terraform init"
        echo "terraform apply -auto-approve"
      env:
        GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

  function-deploy:
    name: Cloud Functions Deployment
    needs: terraform-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Ensure all necessary commits are fetched

    - name: Setup GCP Authentication
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}


    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
#        install_components: "gcloud beta"

    - name: Check for Changes in Functions
      run: |
        echo "Checking for changes in functions..."
        CHANGED_FUNCS=$(git diff --name-only HEAD~1 HEAD | grep '^functions/' | cut -d '/' -f 1-3 | uniq)
        if [ -z "$CHANGED_FUNCS" ]; then
          echo "No functions to deploy."
        else
          echo "CHANGED_FUNCS<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FUNCS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        fi

    - name: Deploy Changed Functions
      if: env.CHANGED_FUNCS
      run: |
        for FUNC_PATH in $CHANGED_FUNCS; do
          FUNCTION_NAME=$(basename $FUNC_PATH)
          echo "Deploying $FUNCTION_NAME..."
          # Your deployment command here, e.g.,
          echo "gcloud functions deploy $FUNCTION_NAME --trigger-http --runtime nodejs14 --source $DIR"
        done
